### ISSUE TITLE
[FEATURE REQUEST] Add support for the native macOS platform

### ISSUE THREAD

**Issue by roman-sundurov** [superwall/Superwall-iOS#208]
I like your service and am creating a native macOS SwiftUI app with RevenueCat. However, when I checked the Superwall documentation for information on native macOS support, I could not find any.
Subsequently, I reached out to your support team and received the following response:

<img width="364" alt="Screenshot 2024-04-25 at 2 23 31 PM" src="https://github.com/superwall/Superwall-iOS/assets/68818066/6397e286-bdce-46f2-bd40-032476ffb11f">

Unfortunately, I cannot use Superwall for my purpose. However, I believe that adding native macOS support to the Superwall service could greatly enhance its usability and attract more users.

**Comment by yusuftor** [comment]
Hey, thanks for the suggestion. You can use Superwall with Mac Catalyst or MacOS (Built for iPad) but yes currently we don't support native SwiftUI mac apps. Definitely something we want to support in the future!

**Comment by yusuftor** [comment]
It's quite far down in our backlog unfortunately. Tentatively looking at Q1 next year

**Comment by ptrkstr** [comment]
@yusuftor was this still planned?
