### ISSUE TITLE
[BUG] Vision OS - 'UIScreen' is unavailable in visionOS

### ISSUE THREAD

**Issue by JazKingX** [superwall/Superwall-iOS#226]
## New issue checklist
- [ ] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [ ] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `Superwall` version:
- iOS version(s):
- CocoaPods/Carthage version (if applicable):
- Xcode version:
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Describe the bug
'UIScreen' is unavailable in visionOS

<img width="1090" alt="Screenshot 2024-07-25 at 12 05 13" src="https://github.com/user-attachments/assets/7dbf99f9-d7b8-4205-9fb5-9f9a101fab0b">

**Comment by yusuftor** [comment]
Thanks for spotting this, will be fixed in the next update!

**Comment by manuelescrig** [comment]
This issue is still happening on the latest release. Would it be possible to fix it? Otherwise, visionOS App with the SDK can't be updated. Thank you!

**Comment by yusuftor** [comment]
Oops, you're right. Have fixed now and will be in the next release, sorry about that!

**Comment by manuelescrig** [comment]
Thank you so much! 🙌
