### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by alexkartsev** [superwall/Superwall-iOS#237]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [] I have attempted to reproduce the issue and include an example project.

### General information

- `Superwall` version: 3.7.4
- iOS version(s): 17.6
- CocoaPods/Carthage version (if applicable):
- Xcode version: 16 RC
- Devices/Simulators affected: any iPhone
- Reproducible in the demo project? (Yes/No):
- Related issues:

### Describe the bug
According to https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes#Known-Issues and https://forums.developer.apple.com/forums/thread/762711 during the release build or launching app from TestFlight there is a crash.

`Symbol not found: _$s10Foundation14NSDecimalRoundyySpySo0B0aG_SPyADGSiSo14NSRoundingModeVtF`

Looks like we can't use `NSDecimalRound` from Swift anymore

### Steps to reproduce
Please also include a description of expected vs. actual behaviour

### Other Information
e.g. stacktraces, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.

**Comment by yusuftor** [comment]
Hi, thanks for reporting. We actually don't need `NSDecimalRound` anymore so I've removed the code associated with that. This fix will be available in the next release.

**Comment by JanGorman** [comment]
Hi – any chance that we'll see a new release available soon? This is affecting our app as well and prevents us from shipping iOS 18 features.

**Comment by yusuftor** [comment]
Hi this is fixed in v3.8.0, released just now!
