### ISSUE TITLE
[BUG] Unable to access configurationStatus before sdk initialization.

### ISSUE THREAD

**Issue by dixit-funnmedia** [superwall/Superwall-iOS#239]
### General information

- `Superwall` version: 3.8.0

### Describe the bug
We are experiencing a crash when checking if the Superwall SDK has been configured. The crash occurs when using the following method:

swift
Superwall.shared.configurationStatus

Steps to Reproduce:
Attempt to check the configuration status of the Superwall SDK using the above method.
If the SDK is not configured, the app crashes immediately.
Expected Behavior: The app should handle the scenario where the SDK is not configured and should either return an appropriate status or throw a recoverable error, instead of crashing.

Actual Behavior: If the SDK is not configured, the app crashes without any error handling or fallback mechanism.

**Comment by yusuftor** [comment]
Hi, replied in slack but replying here too. You don't need to use `configurationStatus`, you should check `Superwall.isInitialized`. When that's `true`, it means that the `shared` instance is available to use and you can set `Superwall.shared.subscriptionStatus`.
