### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tkafka** [superwall/Superwall-iOS#259]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `Superwall` version: 3.11.1
- iOS version(s): macOS 15.0.1
- CocoaPods/Carthage version (if applicable):
- Xcode version: Version 16.1 beta 3 (16B5029d)
- Devices/Simulators affected: Mac Catalyst app
- Reproducible in the demo project? (Yes/No): 
- Related issues:

### Describe the bug
Xcode cloud build for Mac Catalyst fails with `While building for Mac Catalyst, no library for this platform was found in '/Volumes/workspace/DerivedData/SourcePackages/checkouts/Superscript-iOS/Frameworks/libcel.xcframework'.`
<img width="858" alt="image" src="https://github.com/user-attachments/assets/a65d0d20-d902-452e-b2a0-1909da6be3d3">

This makes Superwall-iOS after 3.10.2 unusable for my project.

### Steps to reproduce
Build an app with Superwall 3.11.1 for Mac Catalyst in Xcode Cloud configured to `Latest Release`

<img width="994" alt="image" src="https://github.com/user-attachments/assets/8bcff270-511f-4d41-89d1-6117450d3477">

### Other Information
Let me know if you need more info

**Comment by yusuftor** [comment]
Thanks for pointing this out, we'll take a look on Monday and get back to you ASAP

**Comment by yusuftor** [comment]
Hi, this is fixed in the latest version 3.11.2, please update :)

**Comment by tkafka** [comment]
Awesome, thanks!
