### ISSUE TITLE
[BUG] Cannot find type 'Notification' in scope on visionOS

### ISSUE THREAD

**Issue by seldon1000** [superwall/Superwall-iOS#261]
## New issue checklist
- [ ] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `Superwall` version: 3.10.1
- visionOS version(s): 1.0, 2.0
- Xcode version: 16.0
- Devices/Simulators affected: Apple Vision Pro

### Describe the bug
It is not possible to build for visionOS destinations. 'Notification' is not found in scope.

<img width="1457" alt="image" src="https://github.com/user-attachments/assets/39012d8e-7e9b-40a1-847d-7449874fc4e3">

**Comment by yusuftor** [comment]
Hi, this is fixed in v3.11.0, please update to the latest version.

**Comment by seldon1000** [comment]
> Hi, this is fixed in v3.11.0, please update to the latest version.

I'm experiencing #259 on 3.11 builds. I will update as soon as that's fixed too. Thanks a lot.

**Comment by yusuftor** [comment]
Hi, this is fixed in the latest version 3.11.2, please update :)
