### ISSUE TITLE
[BUG] Latest version does not work on catalyst.

### ISSUE THREAD

**Issue by CamPlan-AI** [superwall/Superwall-iOS#262]
### Description
Building with Mac Catalyst fails due to missing platform support in libcel.xcframework from the Superscript-iOS package.
Error Message
CopyWhile building for Mac Catalyst, no library for this platform was found in '.../Frameworks/libcel.xcframework'
Environment

### Xcode version: [your version]
Superwall package version: [version]
Mac Catalyst target: Yes

### Expected Behavior
libcel.xcframework should include Mac Catalyst binaries for proper cross-platform support.
Current Workaround Needed
Currently need to disable Mac Catalyst or remove framework integration.

### Additional Context
This framework is included in the latest Superwall package and blocks Mac Catalyst builds.

**Comment by jordanZeleny** [comment]
I have the same issue on mac catalyst. going to downgrade back to 3.10.2

**Comment by yusuftor** [comment]
Hi, we'll release an update fixing this soon and I'll let you know when that's released. Thanks for your patience!

**Comment by malinois** [comment]
same issue for me

**Comment by yusuftor** [comment]
Hi, this is fixed in the latest version 3.11.2, please update :)
