### ISSUE TITLE
[BUG] iPad Crash on Launch

### ISSUE THREAD

**Issue by dcrawbuck** [superwall/Superwall-iOS#265]
## New issue checklist
- [X] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [X] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [X] I have attempted to reproduce the issue and include an example project.

### General information

- `Superwall` version: v3.11.3
- iOS version(s): 18.0, 18.1
- CocoaPods/Carthage version (if applicable): n/a
- Xcode version: 16.0
- Devices/Simulators affected: iPad Pro 11-inch 3rd gen, M4
- Reproducible in the demo project? (Yes/No): No

### Describe the bug
Crashes on launch with certain iPads, including simulator. Observed it crashing on iPad Pro 11 in. 3rd gen and M4.

### Steps to reproduce
I was able to reproduce once on a physical device from Testflight and once on simulator, but not since (no code changes). I was not able to reproduce in example project, no obvious difference between example project and mine.

### Other Information
Seems similar to this issue reported to Superwall-Flutter: https://github.com/superwall/Superwall-Flutter/issues/40

Two different but similar stack traces, both on launch on iPads only.

```
Crashed: com.apple.root.user-initiated-qos.cooperative
0                                 0xa7970c AppSessionManager.detectNewSession() + 127 (AppSessionManager.swift:127)
1  libswift_Concurrency.dylib     0x5e8d4 <redacted> + 252
2  libswift_Concurrency.dylib     0x5fde4 <redacted> + 76
3  libdispatch.dylib              0x15d8c <redacted> + 392
4  libdispatch.dylib              0x16590 <redacted> + 156
5  libsystem_pthread.dylib        0x4c40 _pthread_wqthread + 228
6  libsystem_pthread.dylib        0x1488 start_wqthread + 8
        
```

```
Crashed: com.apple.root.user-initiated-qos.cooperative
0                                 0xab4c30 ConfigManager.preloadPaywalls(withIdentifiers:) + 465 (ConfigManager.swift:465)
1  libswift_Concurrency.dylib     0x5e8d4 <redacted> + 252
2  libswift_Concurrency.dylib     0x5fde4 <redacted> + 76
3  libdispatch.dylib              0x15d8c <redacted> + 392
4  libdispatch.dylib              0x16590 <redacted> + 156
5  libsystem_pthread.dylib        0x4c40 _pthread_wqthread + 228
6  libsystem_pthread.dylib        0x1488 start_wqthread + 8
```

**Comment by yusuftor** [comment]
This stack trace looks similar to a crash that was occurring with beta versions of iOS 18. Can you confirm that the affected users are NOT on the beta version?

**Comment by dcrawbuck** [comment]
Ah, that seems to be it then. Affected users are only on the beta and can't reproduce on non-beta iOS. Will close this issue and only reopen if it happens on non-beta (and check the iOS version more closely before reporting next time). Thanks!
