### ISSUE TITLE
[BUG] Crash : [APMMeasurement filterPurchaseTransactions:callback:]_block_invoke + 4309918200

### ISSUE THREAD

**Issue by GreydeskChirag** [superwall/Superwall-iOS#272]
### General information

- `Superwall` version: 3.12.0
- iOS version(s): 14.5
- CocoaPods/Carthage version (if applicable): 1.16.2
- Xcode version: 15.4
- Devices/Simulators affected: Device iPhone XR
- Reproducible in the demo project? (Yes/No): Yes, But not demo, In live app
- Related issues:

### Describe the bug
I opened the sales page and tapped to initiate a purchase, which brought up the Apple purchase sheet. However, after tapping the close button and repeating these steps 4–5 times, the app crashes. I have attached the Firebase crash logs for your reference.

### Steps to reproduce
1. open sales page
2. Tap on purchase button then open apple default purchase form sheet
3. Tap on close button then close apple purchase sheet.
same steps repeat 4 to 5 times.

<img width="1072" alt="Screenshot 2024-11-28 at 12 48 00 PM" src="https://github.com/user-attachments/assets/97498286-d159-4261-b9b8-aab7b99f22d5">

**Comment by yusuftor** [comment]
Hi, can you attach the full stack trace? `APMMeasurement` isn't part of Superwall

**Comment by GreydeskChirag** [comment]
Video link:
https://www.dropbox.com/scl/fi/kizemzqle432njlrrjfs3/Video-28-11-24-3-21-14-PM.mp4?rlkey=gq88rcwe3nvz1stz6pdo8bv2o&st=kh3etpsh&dl=0

**Comment by yusuftor** [comment]
Thanks for the video demonstrating the issue but I need the stack trace to figure out where it's coming from. Can you tap on the crash in Firebase and copy the full stack trace here?

**Comment by GreydeskChirag** [comment]
[com.textstory.story_issue_2667f4bf9b6d3a0f2892c21ebf84ee4c_crash_session_4dd8b4e3ccc549bd93f99fc1013d34d7_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17946404/com.textstory.story_issue_2667f4bf9b6d3a0f2892c21ebf84ee4c_crash_session_4dd8b4e3ccc549bd93f99fc1013d34d7_DNE_0_v2_stacktrace.txt)

**Comment by yusuftor** [comment]
Thanks. It looks like the crash is occurring in a function that no longer exists in version `3.12.0` of the SDK. Can you double check what version of Superwall you're using and can you upgrade to the latest version and see if it still occurs?

**Comment by GreydeskChirag** [comment]
Thanks for update. Yes, It happened in the latest pod version 3.12.1. I have checked at development level and TestFlight build.

**Comment by yusuftor** [comment]
That crash log is coming from v10.14 of your app. When I checked users for your Superwall account who are using that version, they are on an old version of Superwall v3.9.1. Since this code where the crash is occurring doesn't exist now and there have been a lot of fixes since then, it's going to be hard to debug. If you can find a crash using the latest version of your app v10.15 with the SDK v3.12.0, let me know.

**Comment by GreydeskChirag** [comment]
Thank you for the update. The app is crashing in version 10.15. I have attached the stack trace for your reference.
[com.textstory.story_issue_870e3a35c34fa39d5bb57ef4bc9987d0_crash_session_b463b6c5f2a1498fa938ebdf7a43c892_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17954407/com.textstory.story_issue_870e3a35c34fa39d5bb57ef4bc9987d0_crash_session_b463b6c5f2a1498fa938ebdf7a43c892_DNE_0_v2_stacktrace.txt)

**Comment by yusuftor** [comment]
That crash log isn't related to Superwall. That's to do with APMMeasurement which is a Firebase crash. I'm going to close this issue now but if you find a crash to do with Superwall, feel free to reopen it.
