### ISSUE TITLE
Getting warning related to Accessibility (AX) permissions

### ISSUE THREAD

**Issue by dimpy-iroid** [superwall/Superwall-iOS#275]
Unknown client: College Tools
AX Lookup problem - errorCode:1100 error:Permission denied portName:'com.apple.iphone.axserver' PID:806 (
	0   AXRuntime                           0x00000001d4cd5ed4 _AXGetPortFromCache + 796
	1   AXRuntime                           0x00000001d4cda208 AXUIElementPerformFencedActionWithValue + 700
	2   UIKit                               0x00000002583aa764 EE4D5D88-0FE3-30D9-BA13-563EE1B8910F + 1533796
	3   libdispatch.dylib                   0x0000000102a3ca30 _dispatch_call_block_and_release + 32
	4   libdispatch.dylib                   0x0000000102a3e71c _dispatch_client_callout + 20
	5   libdispatch.dylib                   0x0000000102a465e8 _dispatch_lane_serial_drain + 828
	6   libdispatch.dylib                   0x0000000102a47360 _dispatch_lane_invoke + 408
	7   libdispatch.dylib                   0x0000000102a545f0 _dispatch_root_queue_drain_deferred_wlh + 328
	8   libdispatch.dylib                   0x0000000102a53c00 _dispatch_workloop_worker_thread + 580
	9   libsystem_pthread.dylib             0x000000022649bc7c _pthread_wqthread + 288
	10  libsystem_pthread.dylib             0x0000000226498488 start_wqthread + 8
)

I have called Superwall.shared.identify(userId: userId) and on logout, Superwall.shared.reset()

**Comment by yusuftor** [comment]
Hi, the log doesn't seem to be related to Superwall
